### ISSUE TITLE
Allow `clutter find` to receive STDIN

### ISSUE THREAD

**Issue by carlwiedemann** [cluttercode/clutter#1]
A feature of the VS code extension is auto-complete, which detects whether a tag is being typed and provides a list of suggestions.

The suggestions are currently being pulled from `cluter find --no-index`, but this only works on saved files. Which means that auto-complete does not work if you type a tag and then try to type it again in the same file before it is saved.

As a workaround, I have allowed the extension to do its own parsing, it look something like this

```ts
  vscode.workspace.onDidChangeTextDocument((e: vscode.TextDocumentChangeEvent) => {
    let parsed = TagDataSource.parseString(e.document.getText());
    TagDataSource.registerTempTags(e.document.uri.fsPath, parsed);
  });
```

However, instead of having the extension duplicate the parsing logic, it might be better to use the same parsing logic in the CLI tool.

I believe could be accomplished by allowing STDIN to be passed to `clutter find`

e.g. something like this

```
$ cat some_file.go
// hi [#foo#]
// bye [#bar#]

$ cat some_file.go | clutter find --no-index foo
foo STDIN:1.7

$ cat some_file.go | clutter find --no-index bar
bar STDIN:2.8

```

Cheers ✌️

**Comment by itayd** [comment]
done!

**Comment by itayd** [comment]
```
clutter resolve --loc whatever:line.col --loc-from-stdin
```

btw, index is not used by default now.
